### ISSUE TITLE
Graph legends don't render correctly

### ISSUE THREAD

**Issue by laf** [crazy-max/docker-librenms#4]
Not sure where to look into for this but anyone else seeing:

![image](https://user-images.githubusercontent.com/3941142/45933498-31fd3200-bf86-11e8-88f6-3a067071a99f.png)

The legends are completely illegible.

Any ideas?

**Comment by crazy-max** [comment]
Really strange I don't have this issue :

![image](https://user-images.githubusercontent.com/1951866/45981185-6e975f00-c054-11e8-9506-aa3d18bd9a92.png)

Can you post your docker stack pls ?

**Comment by laf** [comment]
Even that image looks odd compared to all of the installs I've ever seen. This is the demo:

![image](https://user-images.githubusercontent.com/3941142/45981590-7bfd1b00-c04d-11e8-8a06-12cefd5d04e4.png)

```
  rrdcached:
    image: crazymax/rrdcached
    volumes:
      - "/mnt/data/librenms/rrd:/data/db"
      - "/mnt/data/rrd-journal:/data/journal"
    environment:
      - "TZ=Europe/Paris"
      - "PUID=1000"
      - "PGID=1000"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
  librenms:
    image: crazymax/librenms:latest
    depends_on:
      - mysql
      - memcached
      - rrdcached
    volumes:
      - "/mnt/data/librenms:/data"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=librenms"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:HOSTNAME"
        - "traefik.frontend.auth.basic=AUTH"
        - "traefik.docker.network=home_default"
    env_file:
      - ./librenms.env
    networks:
      - default

  cron:
    image: crazymax/librenms:latest
    command:
      - "/usr/local/bin/cron"
    depends_on:
      - app
    volumes:
      - "/mnt/data/librenms:/data"
    env_file:
      - ./librenms.env
```
